# -*- coding: utf-8 -*-

"""
    apimaticcalculator.apimatic_calculator_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.simple_calculator_controller import SimpleCalculatorController

class ApimaticcalculatorClient(object):

    config = Configuration

    @lazy_property
    def simple_calculator(self):
        return SimpleCalculatorController()



